version: "3.7"
services:
  spark-master:
    image: koreacb/spark:latest
#    container_name: spark-master
    hostname: spark-master
    ports:
      - "4040:4040"
      - "6066:6066"
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"
      - "8998:8998"
    networks:
      - spark-network
    environment:
#      - "SPARK_LOCAL_IP=localhost"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    volumes:
      - /tmp:/tmp
    command: sh -c "/start-master.sh"

  spark-worker:
    image: koreacb/spark:latest
    depends_on:
      - spark-master
    ports:
      - "8082:8080"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=1G"
    volumes:
      - /tmp:/tmp
    command: sh -c "/start-worker.sh"

networks:
   spark-network:

#   default:
#       external:
#           name: spark

#  spark-network:
#    driver: overlay
